update README, make comments uniform, and add pgsqllat, pgsqlslowest

diff --git a/pgsqlslow b/pgsqlslow
--- a/pgsqlslow
+++ b/pgsqlslow
@@ -7,7 +7,7 @@
 ps_arg0="pgsqlslow"
 
 #
-# Some of this boilerplate is common to pgsqlstat, but it's duplicated here
+# Some of this boilerplate is common to several tools, but it's duplicated here
 # because it's very useful for these to be standalone scripts.
 #
 ps_tmpfile="/var/tmp/$ps_arg0.$$"
@@ -23,11 +23,14 @@ if [[ "$1" == "-h" || "$1" == "--help" ]]; then
 	cat >&2 <<EOF
 $ps_synopsis
 
-Instrument all postgres instances visible on this system and report details
-about queries taking longer than NMILLISECONDS from start to finish.  This tool
-requires privileges to use DTrace on postgres processes on this system.  If you
-see no output but expect some, check whether your user has permissions to trace
-the postgres processes.
+Print details about queries taking longer than NMILLISECONDS from start to
+finish on all postgresql instances on this system.  Note that since this tool
+traces query start to query done, it will never see queries taking longer than
+NMILLISECONDS seconds.
+
+This tool requires privileges to use DTrace on postgres processes on this
+system.  If you see no output but expect some, check whether your user has
+permissions to trace the postgres processes.
 EOF
 	exit 2
 elif ! [[ "$1" -eq "0" || "$1" =~ $ps_number_re ]]; then
@@ -43,7 +46,7 @@ function cleanup
 }
 
 if ! type dtrace > /dev/null 2>&1; then
-	echo "pgsqlstat: requires dtrace(1M), but not found" >&2
+	echo "$ps_arg0: requires dtrace(1M), but not found" >&2
 	exit 1
 fi
 
diff --git a/pgsqlstat b/pgsqlstat
--- a/pgsqlstat
+++ b/pgsqlstat
@@ -1,23 +1,32 @@
 #!/bin/bash
 
 #
-# pgsqlstat: report top-level postgres stats
+# pgsqlstat NSECONDS: report top-level postgres stats
 #
 
-ps_tmpfile="/var/tmp/pgsqlstat.$$"
+ps_arg0="pgsqlstat"
+
+#
+# Some of this boilerplate is common to several tools, but it's duplicated here
+# because it's very useful for these to be standalone scripts.
+#
+ps_tmpfile="/var/tmp/$ps_arg0.$$"
 ps_number_re='^[1-9][0-9]*$'
+ps_synopsis="usage: $ps_arg0 NSECONDS"
 
 if [[ $# == 0 ]]; then
-	echo "usage: pgsqlstat NSECONDS" >&2
+	echo "$ps_synopsis" >&2
 	exit 2
 fi
 
 if [[ "$1" == "-h" || "$1" == "--help" ]]; then
 	cat >&2 <<EOF
-usage: pgsqlstat NSECONDS
+$ps_synopsis
 
-Prints out stats about all postgresql instances visible on this system.
-Columns:
+Prints out stats every NSECONDS about all postgresql instances visible on this
+system.  Use CTRL-C to stop.
+
+Output columns:
 
     QS		Queries started
     QD		Queries completed (both successes and failures)
@@ -38,12 +47,11 @@ Columns:
 This tool requires privileges to use DTrace on postgres processes on this
 system.  If you see all zeroes but expect some data, check whether your user has
 permissions to trace the postgres processes.
-
 EOF
 	exit 2
 elif ! [[ "$1" =~ $ps_number_re ]]; then
-	echo "pgsqlstat: bad number of seconds" >&2
-	echo "usage: pgsqlstat NSECONDS" >&2
+	echo "$ps_arg0: bad number of seconds" >&2
+	echo "$ps_synopsis" >&2
 	exit 2
 fi
 
@@ -54,20 +62,16 @@ function cleanup
 }
 
 if ! type dtrace > /dev/null 2>&1; then
-	echo "pgsqlstat: requires dtrace(1M), but not found" >&2
+	echo "$ps_arg0: requires dtrace(1M), but not found" >&2
 	exit 1
 fi
 
 cat > "$ps_tmpfile" <<EOF
 #!/usr/sbin/dtrace -s
-/* vim: set ft=d: */
 
 #pragma D option quiet
 #pragma D option zdefs
 
-/*
- * pgsqlstat: postgres basic stats tool
- */
 BEGIN
 {
 	@querystarts = sum(0);
